ALTER TABLE products
  ADD COLUMN IF NOT EXISTS labels TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS weave_type TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS handles_count TEXT DEFAULT NULL;
